### ISSUE TITLE
Enable filtering sites in sidebar next to map

### ISSUE THREAD

**Issue by Groschenroman** [tracking-exposed/krgotrex#18]

**Comment by vecna** [comment]
I was looking at it and at the function searchSite. But I feel we should have somewhere the sitesArray (which do not exists in main.js)

How do you want to approach this?

**Comment by vecna** [comment]
Sorry, I've to reopen the issue. The graphic effect add in the last update is nice :) but, try to search for "Goldberg" (as example). Goldberg is a name which exists, but is not visible (it is down do the list), it should be moved on top. We can give a look this evening

**Comment by vecna** [comment]
also, the current master is in production https://kreuzberg.google.tracking.exposed

**Comment by vecna** [comment]
sorry! the bug do not exists!
